version: '3.8'

services:
  web:
    restart: always
    build: ./
    container_name: "web"

    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fullstack

  db:
    restart: always
    image: mongo:5.0
    container_name: "database"
    volumes:
      - /home/lafazan/mongodb/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
