// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "program/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CloseClientDB mocks base method.
func (m *MockStorage) CloseClientDB() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseClientDB")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseClientDB indicates an expected call of CloseClientDB.
func (mr *MockStorageMockRecorder) CloseClientDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseClientDB", reflect.TypeOf((*MockStorage)(nil).CloseClientDB))
}

// FindID mocks base method.
func (m *MockStorage) FindID(id string) (model.Joke, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindID", id)
	ret0, _ := ret[0].(model.Joke)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindID indicates an expected call of FindID.
func (mr *MockStorageMockRecorder) FindID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindID", reflect.TypeOf((*MockStorage)(nil).FindID), id)
}

// Fun mocks base method.
func (m *MockStorage) Fun(limit int64) ([]model.Joke, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fun", limit)
	ret0, _ := ret[0].([]model.Joke)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fun indicates an expected call of Fun.
func (mr *MockStorageMockRecorder) Fun(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fun", reflect.TypeOf((*MockStorage)(nil).Fun), limit)
}

// Random mocks base method.
func (m *MockStorage) Random(limit int) ([]model.Joke, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Random", limit)
	ret0, _ := ret[0].([]model.Joke)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Random indicates an expected call of Random.
func (mr *MockStorageMockRecorder) Random(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Random", reflect.TypeOf((*MockStorage)(nil).Random), limit)
}

// Save mocks base method.
func (m *MockStorage) Save(arg0 model.Joke) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStorageMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorage)(nil).Save), arg0)
}

// TextSearch mocks base method.
func (m *MockStorage) TextSearch(text string) ([]model.Joke, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextSearch", text)
	ret0, _ := ret[0].([]model.Joke)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TextSearch indicates an expected call of TextSearch.
func (mr *MockStorageMockRecorder) TextSearch(text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextSearch", reflect.TypeOf((*MockStorage)(nil).TextSearch), text)
}

// UpdateByID mocks base method.
func (m *MockStorage) UpdateByID(text, id string) (*mongo.UpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", text, id)
	ret0, _ := ret[0].(*mongo.UpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockStorageMockRecorder) UpdateByID(text, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockStorage)(nil).UpdateByID), text, id)
}
